name: crypto-depth-backend-api
version: '0.1.0.0'
category: value
author: Rune K. Svendsen
maintainer: runesvend@gmail.com
copyright: CC0
license: BSD3
github: runeksvendsen/crypto-depth-backend-api
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - CryptoDepth.Backend.Api
  - CryptoDepth.Backend.Types
  dependencies:
  - base >=4.7 && <5
  - servant
  - aeson
  - text
